version: "2.10.2"
services:
  ppm-postgres-db:
   image: postgres
   container_name: ppm-postgres-db
   env_file:
     - .env
   ports:
     - '5433:5432'
   networks:
     - ppm-net
   restart: always
  ppm-service:
    container_name: ppm-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8081:8081'
      - '5005:5005'
    networks:
      - ppm-net
    depends_on:
      - ppm-postgres-db
networks:
  ppm-net:
    name: ppm-net
    attachable: true
    driver: bridge
